# Definition des cibles de compilation
#######################################

SRC_ALGO = deriche.c threshol.c fc.c rl.c norme.c

unix:
	@echo Compilation sous systeme unix
	@make -f Makefile.unix

dsp:
	@echo Compilation pour cible DSP
	@make -f Makefile.dsp

xcim:
	@echo Compilation pour cible DSP/FPGA
	@make -f Makefile.xci
	
